---
title: "FNZ standard grids"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FNZ standard grids}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r echo=TRUE}
library(nzsf)
library(ggspatial)
library(stars)

theme_set(theme_bw() + theme(axis.title = element_blank()))
```

```{r EEZ_eg, fig.height=7, fig.width=7, fig.cap="EEZ (dashed black), box bounding EEZ (dashed red), 50 x 50 km grid (blue), 200 x 200 km grid (grey), origin (green point)."}
eez <- get_statistical_areas(area = "EEZ", proj = proj_nzsf()) 
bb_eez <- st_bbox(eez) %>% st_as_sfc()

grd200_eez <- get_standard_grid(cell_size = 200, bounding_box = st_bbox(eez), return_raster = FALSE)
grd050_eez <- get_standard_grid(cell_size = 50, bounding_box = st_bbox(eez), return_raster = FALSE)

# Plot and check with center point and bounding box
ggplot() +
  geom_sf(data = grd050_eez,  colour = "lightblue",  fill = NA, alpha = 0.5) +
  geom_sf(data = grd200_eez,  colour = "grey",  fill = NA, alpha = 0.5) +
  plot_statistical_areas(area = "EEZ", colour = "black", fill = NA, linetype = "dashed") +
  geom_sf(data = bb_eez, colour = "red", fill = NA, linetype = "dashed") +
  plot_coast(resolution = "low", fill = "black", colour = "black", size = 0.3) +
  geom_point(aes(x = 0, y = -422600), colour = "green") + 
  annotation_scale(location = "tl", unit_category = "metric")
```

```{r CRA1_eg, fig.height=6, fig.width=7, fig.cap="CRA 1 QMA (dashed black), box bounding CRA 1 (dashed red), 50 x 50 km grid (blue), 200 x 200 km grid (grey)."}
cra1 <- get_statistical_areas(area = "CRA", proj = proj_nzsf()) %>% filter(QMA %in% "CRA1")
bb_cra1 <- st_bbox(cra1) %>% st_as_sfc()

grd200_cra1 <- get_standard_grid(cell_size = 200, bounding_box = st_bbox(cra1), return_raster = FALSE)
grd050_cra1 <- get_standard_grid(cell_size = 50, bounding_box = st_bbox(cra1), return_raster = FALSE)

ggplot() +
  geom_sf(data = grd050_cra1,  colour = "lightblue",  fill = NA, alpha = 0.5) +
  geom_sf(data = grd200_cra1,  colour = "grey",  fill = NA, alpha = 0.5) +
  geom_sf(data = cra1, colour = "black", fill = NA, linetype = "dashed") +
  geom_sf(data = bb_cra1, colour = "red", fill = NA, linetype = "dashed") +
  plot_coast(resolution = "low", fill = "black", colour = "black", size = 0.3) +
  annotation_scale(location = "tl", unit_category = "metric") +
  plot_clip(x = grd200_cra1)
```

```{r overlap_eg, fig.height=7, fig.width=7, fig.cap="EEZ 200 x 200 km grid (blue), CRA 1 200 x 200 km grid (dashed red), origin (green point)."}
# Plot and check overlap of two grids
ggplot() +
  geom_sf(data = grd200_eez,  colour = "lightblue",  fill = NA, alpha = 0.5) +
  geom_sf(data = grd200_cra1,  colour = "red",  fill = NA, alpha = 0.5, linetype = "dashed") +
  plot_coast(resolution = "low", fill = "black", colour = "black", size = 0.3) +
  geom_point(aes(x = 0, y = -422600), colour = "green") +
  coord_sf(xlim = c(-4e+05, 2e+05), ylim = c(-422600, 777400))
```

```{r raster, fig.height=7, fig.width=7, fig.cap="EEZ 200 x 200 km grid as polygons (dotted red), EEZ 200 x 200 km grid as raster (blue), origin (green point)."}
# Get standard grid as a raster
r <- get_standard_grid(cell_size = 200, bounding_box = st_bbox(eez), return_raster = TRUE)

# Fill the grid with random values and plot it
r[] <- rnorm(n = ncell(r))
rstar <- st_as_stars(r)

ggplot() +
  geom_stars(data = rstar) +
  geom_sf(data = grd200_eez, fill = NA, colour = "red", linetype = "dotted") +
  plot_coast(resolution = "low", fill = "black", colour = "black", size = 0.3) +
  plot_statistical_areas(area = "EEZ", colour = "black", fill = NA) +
  geom_point(aes(x = 0, y = -422600), colour = "green")
```
