---
title: "nzsf"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nzsf}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(nzsf)
```

# Introduction

A basic map of the New Zealand coastline with a north arrow and a scale bar can be built using:

```{r echo=TRUE, fig.height=6, fig.width=6, message=FALSE}
ggplot() +
  plot_nz(fill = "black", colour = "black", size = 0.3) +
  annotation_north_arrow(location = "tr", which_north = "true", style = north_arrow_nautical) +
  annotation_scale(location = "br", unit_category = "metric")
```

Maps can be built up in layers in the same way as `ggplot2`:

```{r echo=TRUE, fig.height=6, fig.width=6, message=FALSE}
proj <- "+proj=aea +lat_1=-30 +lat_2=-50 +lat=-40 +lon_0=175 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

bbox <- get_coast() %>% 
  st_transform(crs = proj, check = TRUE) %>% 
  filter(name %in% c("North Island or Te Ika-a-MÄui")) %>%
  st_bbox()

ggplot() +
  plot_marine_reserves(fill = "green", colour = "green") +
  plot_qma(qma = "CRA", fill = NA) +
  plot_nz(fill = "black", colour = "black", size = 0.3) +
  annotation_north_arrow(location = "tr", which_north = "true", style = north_arrow_nautical) +
  annotation_scale(location = "br", unit_category = "metric") +
  coord_sf(xlim = bbox[c(1,3)], ylim = bbox[c(2,4)])
```
