---
title: "Projections"
format:
  html:
    toc: true
    toc-depth: 2
vignette: >
  %\VignetteIndexEntry{Projections}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{quarto::html}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
)
set.seed(4277)
```

```{r echo=TRUE}
library(nzsf)
library(ggplot2)
library(sf)
theme_set(theme_bw() + theme(axis.title = element_blank()))
```

```{r}
#| label: fig-nz-albers
#| fig-cap: The New Zealand EEZ (dashed black lines) and the projection centre (green point).
#| 
get_projection_center <- function(proj) {
  crs_info <- st_crs(proj)
  lat_0 <- as.numeric(gsub(".*lat_0=([-0-9.]+).*", "\\1", crs_info$input))
  lon_0 <- as.numeric(gsub(".*lon_0=([-0-9.]+).*", "\\1", crs_info$input))
  return(list(lon = lon_0, lat = lat_0))
}

x <- get_projection_center(proj_nzsf())

points_df <- st_as_sf(
  data.frame(lon = x$lon, lat = x$lat),
  coords = c("lon", "lat"),
  crs = 4326
)
points_df <- st_transform(points_df, crs = proj_nzsf())

ggplot() +
  plot_statistical_areas(area = "EEZ", colour = "black", fill = NA, linetype = "dashed") +
  plot_coast(resolution = "medium", fill = "black", colour = "black") +
  geom_sf(data = points_df, colour = "green") + 
  plot_clip("NZ")
```
